version: "3"

services:
  server-01:
    build: ./server-01
    ports:
      - "8001"
  server-02:
    build: ./server-02
    ports:
      - "8002"
  server-03:
    build: ./server-03
    ports:
      - "8003"
  load-balancer:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - nginx-vol:/etc/nginx

volumes:
  nginx-vol:
